name: Run Web Scrapers

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch the last 2 commits to check commit message

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt

      - name: Scrape UF course data for Fall 2026 and Spring 2027
        run: python pythonScripts/UFCourseGrabber.py fall 26 spring 27
        env:
          UF_COOKIE: ${{ secrets.UF_COOKIE }}

      - name: Run second script
        run: python pythonScripts/scrapeRMP.py

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and conditionally amend previous commit
        run: |
          git add -A
          if ! git diff --staged --quiet; then
            LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
            if [ "$LAST_COMMIT_MSG" = "Hourly update from web scrapers" ]; then
              git commit --amend --no-edit
            else
              git commit -m "Hourly update from web scrapers"
            fi
            git push --force
          fi
